version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mlip_dev_container
    restart: always
    command: ["/bin/sh","-c","--","while true; do sleep 84600; done"]
    volumes:
      - code:/workspace
volumes:
  code: